# -*- coding: utf-8 -*-
"""variance threshold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177dUEY6Uk6xS7QQQrJ-ejzdwMXRVIq8B
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import VarianceThreshold
from six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus

col_names = ['age','sex','cp','trestbps','chol','fbs',
             'restecg','thalach','exang','oldpeak',
             'slope','ca','thal']

# Load dataset
ds = pd.read_csv('heart.csv',
                 encoding="ISO-8859-1")

print(ds)

# Split dataset into features and target variable
X = ds[col_names]     # Features
y = ds["target"]      # Target variable

# -----------------------------------
# Feature Selection using Variance Threshold
# -----------------------------------

# Apply Variance Threshold
selector = VarianceThreshold(threshold=0.1)

X_new = selector.fit_transform(X)

# Get selected feature names
selected_features = X.columns[selector.get_support()]

# Create dataframe for variance scores
feature_scores = pd.DataFrame({
    'Feature': col_names,
    'Variance_Score': X.var().values
})

# Sort features based on variance
feature_scores = feature_scores.sort_values(
    by='Variance_Score',
    ascending=False
)

print("\nFeature Selection using Variance Threshold")
print(feature_scores)

print("\nSelected Features:")
print(selected_features.tolist()[0:8])

# Use selected features
X = ds[selected_features.tolist()[0:8]]

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=1
)

# Create Decision Tree classifier object
clf = DecisionTreeClassifier()

# Train Decision Tree classifier
clf = clf.fit(X_train, y_train)

# Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy
print("Accuracy (%):",
      metrics.accuracy_score(y_test, y_pred) * 100)

predicted = y_pred
xtest = X_test
ytest = y_test

print(f'predicted all rows {xtest} ==== {predicted} \n Actual {ytest}.\n')

from sklearn.metrics import accuracy_score
print('Accuracy DT..................')
print(accuracy_score(predicted, ytest))

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print("confusion_matrix = ")
print(confusion_matrix(ytest, predicted))

print(classification_report(ytest, predicted))

# Decision Tree Visualization
dot_data = StringIO()

export_graphviz(
    clf,
    out_file=dot_data,
    filled=True,
    rounded=True,
    special_characters=True,
    feature_names=selected_features.tolist()[0:8]
)

graph = pydotplus.graph_from_dot_data(
    dot_data.getvalue()
)

Image(graph.create_png())